from core_business_cycle.core_business_cycle.utils.selling.delivery_note.delivery_note_custom_fields import delivery_note_customization
from core_business_cycle.core_business_cycle.utils.buying.purchase_receipt.purchase_receipt_custom_fields import purchase_receipt_customization
from core_business_cycle.core_business_cycle.utils.selling.sales_invoice.sales_invoice_custom_fields import sales_invoice_customization
from core_business_cycle.core_business_cycle.utils.stock.stock_entry.stock_entry_custom_field import stock_entry_customization
from core_business_cycle.core_business_cycle.utils.stock.stock_reconciliation.stock_reconciliation_custom_fields import stock_reconciliation_customization
from core_business_cycle.core_business_cycle.utils.buying.purchase_invoice.purchase_invoice_custom_fields import purchase_invoice_customization
def after_install():
    delivery_note_customization()
    purchase_receipt_customization()
    sales_invoice_customization()
    stock_entry_customization()
    stock_reconciliation_customization()
    purchase_invoice_customization()